// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testsize.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ThingWithSize struct {
	Size                 uint64   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingWithSize) Reset()         { *m = ThingWithSize{} }
func (m *ThingWithSize) String() string { return proto.CompactTextString(m) }
func (*ThingWithSize) ProtoMessage()    {}
func (*ThingWithSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc98140747dcb30, []int{0}
}

func (m *ThingWithSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingWithSize.Unmarshal(m, b)
}
func (m *ThingWithSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingWithSize.Marshal(b, m, deterministic)
}
func (m *ThingWithSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingWithSize.Merge(m, src)
}
func (m *ThingWithSize) XXX_Size() int {
	return xxx_messageInfo_ThingWithSize.Size(m)
}
func (m *ThingWithSize) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingWithSize.DiscardUnknown(m)
}

var xxx_messageInfo_ThingWithSize proto.InternalMessageInfo

func (m *ThingWithSize) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*ThingWithSize)(nil), "proto.ThingWithSize")
}

func init() { proto.RegisterFile("testsize.proto", fileDescriptor_adc98140747dcb30) }

var fileDescriptor_adc98140747dcb30 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0x2d, 0x2e,
	0x29, 0xce, 0xac, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x66,
	0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xb9, 0xe5, 0x99, 0x25, 0xd9,
	0xf9, 0xe5, 0xfa, 0xe9, 0xf9, 0xba, 0x60, 0x49, 0xdd, 0xb2, 0xc4, 0x9c, 0xcc, 0x94, 0xc4, 0x92,
	0xfc, 0xa2, 0x62, 0x7d, 0x38, 0x13, 0xa2, 0x5d, 0x49, 0x9b, 0x8b, 0x37, 0x24, 0x23, 0x33, 0x2f,
	0x3d, 0x3c, 0xb3, 0x24, 0x23, 0x38, 0xb3, 0x2a, 0x55, 0x48, 0x8a, 0x8b, 0x05, 0x64, 0xba, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x8b, 0x13, 0xdb, 0xa3, 0xfb, 0xf2, 0x4c, 0x02, 0x0c, 0x41, 0x60, 0x31,
	0x27, 0xdd, 0x28, 0x6d, 0x24, 0x6b, 0xca, 0x52, 0xd3, 0x13, 0xc1, 0x86, 0x24, 0xe7, 0xe7, 0xe8,
	0x83, 0x5c, 0x05, 0xe6, 0x80, 0x14, 0xea, 0x83, 0x59, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x49, 0x80, 0x7e, 0x1b, 0xb3, 0x00, 0x00, 0x00,
}
